[package]
name = "readabile_url"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
readability = { version = "0.3.0", default-features = false }
reqwest = { version = "0.12.9", features = ["blocking"] }
